### ISSUE TITLE
RestOfLine fails when not the first positional argument.

### ISSUE THREAD

**Issue by adribona** [reubeno/NClap#11]
It appears the rest of the line is still parsed as arguments when there is a required or positional argument before the rest-of-line argument.

**Comment by reubeno** [comment]
I've added a few unit tests to cover this case--they seem to be working fine now.  Either this has since been fixed or I don't quite have the right way to reproduce it.  I'll close the issue, but please feel free to reopen it if you still see a behavior that you don't expect.
