### ISSUE TITLE
Revisit dynamic selection of ArgumentSet style based on host platform

### ISSUE THREAD

**Issue by reubeno** [reubeno/NClap#23]
It's certainly complicated our tests, and for tools expected to run on multiple host platforms, the default behavior of using different styles by default across them might be confusing.  There's already a way for the program author to be explicit and select the same one across all, but we should probably revisit this decision.

Ideally, user feedback would be helpful here.

**Comment by joelday** [comment]
Slightly related, I'd like to see the short name for Help be 'h' rather than '?' on non-Windows platforms.

**Comment by reubeno** [comment]
I'm glad to hear that you find this library useful!

For feature/change requests (as well as bugs and any other ideas for the future), feel free to just file separate issues here in the GitHub project .  No request is too small or large--we just might not be able to get to addressing them all immediately :).  If you have the time and resources to make changes yourself, we're also happy to review Pull Requests from anyone and everyone!

As for chatting, I've set up a gitter chat environment for this project: https://gitter.im/NClap

Feel free to start chatting there if you're looking for more IM conversation...

**Comment by reubeno** [comment]
Oh, and I've filed a separate issue for your specific '?' vs. 'h' request.

**Comment by reubeno** [comment]
All of the issues described in this thread have been separately tracked (and some resolved).  As for the main topic: whether we should have a differently default style on different host OSes, there's no clear verdict as to which single style to snap to.  We'll close this issue for the meantime and wait for more feedback on whether it's confusing for tools built with NClap to default to different styles on different OSes.  We're happy to reopen this topic when there's feedback.
