### ISSUE TITLE
Unit test for console scrolling always fails due to parameter validation

### ISSUE THREAD

**Issue by cjoprey** [reubeno/NClap#63]
TestThatScrollingPositiveLinesEitherSucceedsOrThrowsNotSupportedException in WindowConsoleTests.cs (line 51) always fails.

The reason is as follows:
- “console.ScrollContents(1)” calls “CursorTop -= lineCount” (WindowsConsole.cs, line 68)
- CursorTop is based on “_cursorTop”
- “_cursorTop” has a default value of zero, and a validator that it must be >= 0.
- That first line I mentioned tries to set CursorTop to -1, so it will always fail.

The test indicates that if _consoleTop is set to a negative number, it should throw a NotSupportedException, rather than the ArgumentOutOfRangeException it throws now due to the validation failure.

Should we change the test, or should we change the code?

**Comment by reubeno** [comment]
We should change both!  Thank you for the detailed analysis -- it made it very easy to sort out what's going on here.

**Comment by reubeno** [comment]
Should be fixed now, but please reactivate if you still see this.
