### ISSUE TITLE
Autocomplete from Array

### ISSUE THREAD

**Issue by javierbarre** [reubeno/NClap#69]
Is there any way to "autocomplete" the possible values of a NamedArgument from an array instead of a ENUM? Since it is dynamic in runtime, it will be great to autocomplete from a dynamic resource.

**Comment by javierbarre** [comment]
Sorry. I just found the Type Completer in ArgumentBaseAttribute.
Is there any documentation available?

**Comment by reubeno** [comment]
No there’s no more documentation than the details on that attribute property. You would need to specify the Completer property as part of a named or positional argument attribute; the value of the porperty should be typeof(T) where T is the name of a class that you provide and which implements IStringCompleter. The interface for IStringCompleter contains a single method that should be fairly well self-described. 

Don’t hesitate to ask if you have additional questions, though!
