### ISSUE TITLE
Set of questions using Loop

### ISSUE THREAD

**Issue by javierbarre** [reubeno/NClap#70]
I am using Loop interface. I have some issues with the style "--" , help and autocomplete:

1.  HELP command is not showing examples using Loop.

2. Cannot get the Loop working with "--" GetOpt style

```C#
[ArgumentSet(
        Style = ArgumentSetStyle.GetOpt,
        Description = "You are cool command.",
        Examples = new string[]
        {
            "cool --myvalue ",
            "",
        })]
class MyCoolCommand : SynchronousCommand
{ ... }
```

```C#
 var setAtt = new ArgumentSetAttribute()
            {
                Style = ArgumentSetStyle.GetOpt,
                NamedArgumentPrefixes = new [] { "--" },
                ShortNameArgumentPrefixes = new [] { "-" },
            };
```

Any ideas?

**Comment by reubeno** [comment]
Could you share the full code you're using to instantiate the loop?  I'll see if I can reproduce the problem and sort it out.

**Comment by reubeno** [comment]
I'm closing this out as I haven't seen a response from the original poster. Please feel free to file additional issues for any continuing problems.
