### ISSUE TITLE
[NamedArgument(ArgumentFlags.MultipleUnique)] doesn't assert unique requirements if you pass in a comma-separated list

### ISSUE THREAD

**Issue by cjoprey** [reubeno/NClap#73]
If I create a command with a "multiple unique" argument as per the title, I have two ways of calling it:

-param <value 1> -param <value 2>
The above works and will show an error message if you pass in the same value for both.

-param <value 1>,<value 2>
This will NOT show an error message if the values are the same.

They should both fail in the same way.

**Comment by reubeno** [comment]
Thanks for catching this!  Looks like a logic error in the validation logic for collections.  We were checking that the new collection values didn't overlap existing ones from previously parsed arguments, but weren't checking that the collection values from the current argument were distinct.  Submitting PR shortly with new unit test case + fix.

**Comment by reubeno** [comment]
Fixed.

**Comment by cjoprey** [comment]
Thanks for the swift fix Reuben!
