### ISSUE TITLE
Help with a wizard interface

### ISSUE THREAD

**Issue by bkapellusch** [reubeno/NClap#82]
Hi, 

 What I'm looking to do is create a simple CRUD console app where I'm planning on prompting the user for each field value, and using the tab autocomplete feature of NClap to do some lookups for things that would be human-readable values for things that would be normally foreign key numeric ids. 

  How would be the best way to have a series of predefined prompts. Would each prompt be a command in a loop? Or should a single command be used to handle all interactions specific to one row of data to add?

I know this isn't the ideal use case for a console app, but I've got a 2 day window to get this done for a hack-a-thon-esque project and I thought it sounded like fun.

Thanks!

**Comment by reubeno** [comment]
Could you share a quick concrete example so I can better understand what you're looking for?  (Feel free to abstract it a bit if this is proprietary/private information.)  My understanding thus far is that you're looking to implement an app that accepts data entry of rows, each of which contain multiple fields (each of which has a specific format).  Is that right?

**Comment by bkapellusch** [comment]
Sure. So my top level commands are:

Add (add an entity)
List (list entities)
Help
Exit

Add and List have sub-commands relating to each entity:

(add)
AddOrganizationType
AddOrganization

(list)
List OrganizationType
List Organization

After that, I'm stuck.  List doesn't need any subcommands or workflow, because it's just a dump of the table contents. But Add would either need all the property values on one line (properties for Organization would be Code (string), Description (string) and OrganizationType (essentially a foreign key, although I'd like to use the autocomplete functionality NClap provides to make it easier to enter that value by looking up all EntityTypes) or ideally, I'd like each property of the entity we're adding to be prompted as its own entry. That way I could further limit the data that the user could enter (for things like business rule constraints).

Does that make sense? Thanks for any help you can provide!

**Comment by reubeno** [comment]
Got it.  Yes, you could have the add command take optional named parameters, e.g.:

    add -code something -description "some description" -org MyOrganizationType

This would work with tab completion.  You could use positional parameters instead if there's a consistent order of the fields that the user will know, .e.g:

    add something "some description" MyOrganizationType

An alternative would be to have each of the fields be a separate subcommand, e.g.:

    add code <code>
    add description <description>

This would support tab-completing on the field 'name', but would require the user to know which field they're looking to add.

For a sequential prompt like you're talking about as your ideal, you could implement the prompting in the command's implementation.  Unfortunately, it looks like some of the classes you'd find most useful in implementing this with tab completion are marked internal-only in NClap; in particular, `ConsoleReader`.  As a result, you'd be constrained to prompting and parsing input lines that start with a 'command', which probably isn't really what you're looking for here.  The string completion facilities are exposed, but the logic that ties them together with watching for the tab-character and doing the right thing is what's buried :-/.  Opportunity for future improvement, for sure, but not something I have time for right now.

Does this help?

**Comment by reubeno** [comment]
I haven't heard any more on this issue, so I'm going to close it out.  If you have any more questions, please feel free to open a new issue.
